import { z } from "zod";
import type { ScanRun, ThreatModel } from "../domain";
import { threatCategorySchema } from "../domain";
import { tolerantString, tolerantStringArray } from "./zod-helpers";

const agentArchitectureSchema = z.object({
  applicationType: tolerantString.default(""),
  summary: tolerantString.default(""),
  technologies: tolerantStringArray(),
});

const agentAssetSchema = z.object({
  id: tolerantString.default(""),
  name: tolerantString.default(""),
  description: tolerantString.default(""),
  sensitivity: tolerantString.default("medium"),
});

const agentTrustBoundarySchema = z.object({
  id: tolerantString.default(""),
  name: tolerantString.default(""),
  description: tolerantString.default(""),
  crossingEntrypoints: tolerantStringArray(),
});

const agentEntrypointSchema = z.object({
  id: tolerantString.default(""),
  name: tolerantString.default(""),
  kind: tolerantString.default(""),
  location: tolerantString.default(""),
  description: tolerantString.default(""),
});

const agentDataFlowSchema = z.object({
  id: tolerantString.default(""),
  name: tolerantString.default(""),
  source: tolerantString.default(""),
  destination: tolerantString.default(""),
  description: tolerantString.default(""),
  assets: tolerantStringArray(),
});

const agentThreatSchema = z.object({
  id: tolerantString.default(""),
  title: tolerantString.default(""),
  category: tolerantString.default("business-logic"),
  severity: tolerantString.default("medium"),
  likelihood: tolerantString.default("medium"),
  affectedAssets: tolerantStringArray(),
  entrypoints: tolerantStringArray(),
  trustBoundaries: tolerantStringArray(),
  rationale: tolerantString.default(""),
  validationIdeas: tolerantStringArray(),
});

const agentFocusAreaSchema = z.object({
  id: tolerantString.default(""),
  title: tolerantString.default(""),
  rationale: tolerantString.default(""),
  preferredValidators: z.array(z.enum(["browser", "ios-simulator"])).default([]),
});

export const threatModelAgentOutputSchema = z.object({
  summary: tolerantString.default("Threat model generated by agent."),
  architecture: agentArchitectureSchema.default({
    applicationType: "",
    summary: "",
    technologies: [],
  }),
  assets: z.array(agentAssetSchema).default([]),
  trustBoundaries: z.array(agentTrustBoundarySchema).default([]),
  entrypoints: z.array(agentEntrypointSchema).default([]),
  dataFlows: z.array(agentDataFlowSchema).default([]),
  assumptions: tolerantStringArray(),
  threats: z.array(agentThreatSchema).default([]),
  recommendedFocusAreas: z.array(agentFocusAreaSchema).default([]),
});
export type ThreatModelAgentOutput = z.infer<typeof threatModelAgentOutputSchema>;

export function normalizeThreatModelAgentOutput(
  run: ScanRun,
  output: ThreatModelAgentOutput,
  transcriptRef?: string,
): ThreatModel {
  const model: ThreatModel = {
    id: crypto.randomUUID(),
    runId: run.id,
    generatedAt: new Date().toISOString(),
    summary: output.summary,
    architecture: {
      applicationType: output.architecture.applicationType || "Source directory application",
      summary: output.architecture.summary || "Architecture summary was not provided by the agent.",
      technologies: output.architecture.technologies,
    },
    assets: output.assets
      .filter((asset) => asset.name.trim())
      .map((asset, index) => ({
        id: asset.id || stableId("asset", asset.name, index),
        name: asset.name,
        description: asset.description || "Security-relevant asset.",
        sensitivity: normalizeSensitivity(asset.sensitivity),
      })),
    trustBoundaries: output.trustBoundaries
      .filter((boundary) => boundary.name.trim())
      .map((boundary, index) => ({
        ...boundary,
        id: boundary.id || stableId("boundary", boundary.name, index),
      })),
    entrypoints: output.entrypoints
      .filter((entrypoint) => entrypoint.name.trim())
      .map((entrypoint, index) => ({
        id: entrypoint.id || stableId("entrypoint", entrypoint.name, index),
        name: entrypoint.name,
        kind: entrypoint.kind,
        ...(entrypoint.location ? { location: entrypoint.location } : {}),
        description: entrypoint.description,
      })),
    dataFlows: output.dataFlows
      .filter((flow) => flow.name.trim())
      .map((flow, index) => ({
        ...flow,
        id: flow.id || stableId("flow", flow.name, index),
      })),
    assumptions: output.assumptions,
    threats: output.threats
      .filter((threat) => threat.title.trim())
      .map((threat, index) => ({
        id: threat.id || stableId("threat", threat.title, index),
        title: threat.title,
        category: normalizeThreatCategory(threat.category),
        severity: normalizeSeverity(threat.severity),
        likelihood: normalizeLikelihood(threat.likelihood),
        affectedAssets: threat.affectedAssets,
        entrypoints: threat.entrypoints,
        trustBoundaries: threat.trustBoundaries,
        rationale: threat.rationale,
        validationIdeas: threat.validationIdeas,
      })),
    recommendedFocusAreas: output.recommendedFocusAreas
      .filter((area) => area.title.trim())
      .map((area, index) => ({
        ...area,
        id: area.id || stableId("focus", area.title, index),
      })),
    ...(transcriptRef ? { transcriptRef } : {}),
  };
  return model;
}

function normalizeSensitivity(value: string): "low" | "medium" | "high" {
  const normalized = value.toLowerCase();
  if (["critical", "sensitive", "secret", "high"].includes(normalized)) return "high";
  if (["moderate", "medium"].includes(normalized)) return "medium";
  return "low";
}

function normalizeSeverity(value: string): "info" | "low" | "medium" | "high" | "critical" {
  const normalized = value.toLowerCase();
  if (["critical", "high", "medium", "low", "info"].includes(normalized))
    return normalized as "info" | "low" | "medium" | "high" | "critical";
  if (["informational", "none"].includes(normalized)) return "info";
  return "medium";
}

function normalizeLikelihood(value: string): "low" | "medium" | "high" {
  const normalized = value.toLowerCase();
  if (normalized === "high" || normalized === "likely") return "high";
  if (normalized === "low" || normalized === "unlikely") return "low";
  return "medium";
}

function normalizeThreatCategory(value: string) {
  const normalized = value.toLowerCase().replace(/_/g, "-");
  const parsed = threatCategorySchema.safeParse(normalized);
  return parsed.success ? parsed.data : "business-logic";
}

function stableId(prefix: string, value: string, index: number): string {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);
  return `${prefix}-${slug || index + 1}`;
}
